from tc_sim.circuit import node_values_to_str
from tc_sim.deductive_fault_simulator import DFSWrapper
from tc_sim.podem import PODEMWrapper
from tc_sim.fault import SSAFault
class CrossVerification:
    def __init__(self, circuit_file: str, fault_file: str):
        self.dfs_wrapper = DFSWrapper(circuit_file)
        self.podem_wrapper = PODEMWrapper(circuit_file)
        self.podem_wrapper.add_faults_from_file(fault_file)
        self.faults: list[SSAFault] = self.podem_wrapper.get_all_faults()

    def cross_verify(self):
        failure_count = 0
        for fault in self.faults:
            test_pattern = self.podem_wrapper.run(fault)
            str_test_pattern = node_values_to_str(test_pattern)
            if "1" not in str_test_pattern and "0" not in str_test_pattern:
                print(f"{fault.get_formatted_string()} is not detected by PODEM")
                continue
            detected_faults = self.dfs_wrapper.run(str_test_pattern)
            if fault in detected_faults:
                pass
            else:
                failure_count += 1
                print(f"{fault.get_formatted_string()}: {str_test_pattern} generated by PODEM not detected by DFS")

        return failure_count
