"""
Cross-verification module for validating PODEM and DFS results.

This module provides functionality to verify that test patterns generated by PODEM
successfully detect faults when validated through Deductive Fault Simulation (DFS).
"""

from tc_sim.circuit import node_values_to_str
from tc_sim.deductive_fault_simulator import DFSWrapper
from tc_sim.podem import PODEMWrapper
from tc_sim.fault import SSAFault


class CrossVerification:
    """
    Cross-verification class to validate consistency between PODEM and DFS.
    
    This class generates test patterns using PODEM and verifies that those patterns
    actually detect the target faults when run through DFS. Any discrepancies indicate
    potential issues in either algorithm.
    
    Attributes:
        dfs_wrapper: Wrapper for Deductive Fault Simulation
        podem_wrapper: Wrapper for PODEM test generation
        faults: List of faults to verify
    """
    
    def __init__(self, circuit_file: str, fault_file: str):
        """
        Initialize the cross-verification system.
        
        Args:
            circuit_file: Path to the circuit netlist file
            fault_file: Path to the fault list file
        """
        # Initialize DFS wrapper for fault detection
        self.dfs_wrapper = DFSWrapper(circuit_file)
        
        # Initialize PODEM wrapper for test generation
        self.podem_wrapper = PODEMWrapper(circuit_file)
        self.podem_wrapper.add_faults_from_file(fault_file)
        
        # Store the list of faults to verify
        self.faults: list[SSAFault] = self.podem_wrapper.get_all_faults()

    def cross_verify(self) -> int:
        """
        Perform cross-verification between PODEM and DFS for all faults.
        
        For each fault:
        1. Generate a test pattern using PODEM
        2. Run that pattern through DFS
        3. Verify that DFS detects the same fault
        
        Returns:
            The number of failures (faults where PODEM and DFS disagree)
        """
        failure_count = 0
        
        for fault in self.faults:
            # Generate test pattern using PODEM
            test_pattern = self.podem_wrapper.run(fault)
            str_test_pattern = node_values_to_str(test_pattern)
            
            # Check if PODEM found a valid test pattern
            if "1" not in str_test_pattern and "0" not in str_test_pattern:
                print(f"{fault.get_formatted_string()} is not detected by PODEM")
                continue
            
            # Verify the test pattern using DFS
            detected_faults = self.dfs_wrapper.run(str_test_pattern)
            
            # Check if DFS detects the same fault
            if fault in detected_faults:
                # Success: PODEM and DFS agree
                pass
            else:
                # Failure: PODEM generated a pattern that DFS doesn't confirm
                failure_count += 1
                print(f"{fault.get_formatted_string()}: {str_test_pattern} "
                      f"generated by PODEM not detected by DFS")

        return failure_count
